GitHub Actions migration added examples and images to tabs
semaphoreci/semaphore pull request #205
Opened 2024-09-11 12:40 UTC by csidyel

## What
GitHub Actions migration page: fixed some text typos and similar. Added images to the tabs. Redid the complete examples.

## Why

## Checklist: 
 

Use a checklist to confirm:
- [x] The branch is up-to-date with the main branch.
- [x] Update follows the docs [style guide](../../docs/docs-contributing/STYLE_GUIDE.md).
- [x] Changes have been tested locally.

2024-09-11 16:25 UTC, TomFern commented
@csidyel does the build work on your machine? When I try to start the main branch in this repo I get this error:

```
Error: MDX compilation failed for file "/Users/tom/r/semaphore-christian/docs/docs/getting-started/migration/github-actions.md"
Cause: Unexpected closing tag `</Tabs>`, expected corresponding closing tag for `<TabItem>` (70:1-70:46)
Details:
{
  "column": 1,
  "message": "Unexpected closing tag `</Tabs>`, expected corresponding closing tag for `<TabItem>` (70:1-70:46)",
  "line": 74,
  "name": "74:1-74:8",
  "place": {
    "start": {
      "line": 74,
      "column": 1,
      "offset": 2241,
      "_index": 125,
      "_bufferIndex": 0
    },
    "end": {
      "line": 74,
      "column": 8,
      "offset": 2248,
      "_index": 126,
      "_bufferIndex": -1
    }
  },
  "reason": "Unexpected closing tag `</Tabs>`, expected corresponding closing tag for `<TabItem>` (70:1-70:46)",
  "ruleId": "end-tag-mismatch",
  "source": "mdast-util-mdx-jsx"
}
```

2024-09-11 16:35 UTC, TomFern commented
I found the fix, actually there are two things you need to fix the build 

On `docs/getting-started/migration/github-actions.md`:
- Line 260: replace `value="semaphore"` with `value="ui"`
- Line 74: add `</TabItem>` before `</Tabs>`

That should build the page. Overall I think **it's a great tutorial** and the tabs really helped. My only observation is that I think the UI screenshot should show the same commands as in the YAML. Otherwise the image and the Semaphore YAML dont' really coincide.

You can highlight the relevant YAML like this:

- Highlight range:

    ```yaml
    checkout
    # highlight-start
    sem-version node 20
    # highlight-end
    ```

- Or one line:

      ```yaml
      checkout
      # highlight-next-line
      sem-version node 20
      ```

2024-09-11 16:40 UTC, TomFern requested changes
@csidyel thank you so much for the PR. Amost there! There are a couple of notes to revise.

2024-09-11 16:40 UTC, TomFern commented on docs/docs/getting-started/migration/github-actions.md
>  </Tabs>
```suggestion
</TabItem>
</Tabs>
```

2024-09-11 16:40 UTC, TomFern commented on docs/docs/getting-started/migration/github-actions.md
> +<TabItem value="semaphore" label="Semaphore YAML">
```suggestion
<TabItem value="ui" label="Semaphore Editor">
```

2024-09-11 16:40 UTC, TomFern commented on docs/docs/getting-started/migration/github-actions.md
> +```yaml
The YAML and the UI screenshot do not have the same commands. I think the tabs Semaphore YAML and Semaphore Editor should always coincide.

There are other examples of this below.

2024-09-12 12:49 UTC, csidyel commented
@TomFern I addressed all the requested changes and uploaded new images. Please, check it out now.

2024-09-12 12:49 UTC, csidyel reviewed
Issues addressed.

2024-09-12 22:19 UTC, TomFern approved these changes
@csidyel perfect thank you! Great work.

Tip for future screenshots: disable Grammarly and spell checking in the textboxes. This is just a detail, nothing major, but it's nice to remove all distractions.

2024-09-12 22:19 UTC, merged